version: '3'
services:
  backend:
    build: ./backend
    command: npm run dev
    ports:
      - '4000:4000'
    volumes:
      - ./backend:/app
  frontend:
    build: ./frontend
    command: npm run dev
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:4000
